### ISSUE TITLE
Updating vocabs in atlas-covid19.ohdsi.org / atlas.ohdsi.org

### ISSUE THREAD

**Issue by kmkostka** [OHDSI/Covid-19#15]
In response to the inclusion of these new vocabulary terms: https://github.com/OHDSI/Vocabulary-v5.0/issues/321

Can we push a vocabulary update to the public COVID ATLAS (atlas-covid19.ohdsi.org) and the controlled ATLAS (atlas.ohdsi.org)? These codes are used by [N3C in their COVID-19 Phenotype](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/wiki/Latest-Phenotype). We would like to build a publicly retrievable phenotype.

**Comment by kmkostka** [comment]
@leeevans Can you help with this?

**Comment by leeevans** [comment]
@kmkostka please see my response on Teams
