### ISSUE TITLE
New vocabulary for novel concepts

### ISSUE THREAD

**Issue by chandryou** [OHDSI/Covid-19#7]
We need the new vocabulary for novel concepts including 'RT-PCR test for SARS-CoV-2' and 'COVID', and mapping table between EDI and standard OMOP vocabulary for them.

**Comment by vojtechhuser** [comment]
LOINC created such code. I posted on LOINC forum a coment about it but it is under moderation. (my guess is they will not approve the post). E.g., temp code don't display what is the LP code for 'SARS-CoV-2 RNA' (for example)

**Comment by chandryou** [comment]
I uploaded novel vocabulary of Korea for COVID-19 to the [wiki](https://github.com/OHDSI/Covid-19/wiki/Novel-vocabulary-for-COVID-19)

Needs mapping to the standard vocabulary

**Comment by dimshitc** [comment]
SNOMED was updated with new COVID concepts added, please see here:
https://forums.ohdsi.org/t/ohdsi-virtual-study-a-thon-to-support-covid-19-response-to-take-place-26-29mar2020-collaborators-wanted/9810/20

ICDs and LOINC updates are coming soon

**Comment by chandryou** [comment]
@dimshitc  @cgreich @Alexdavv 
Will you add more? Or can we close this issue? 
I'd like to update the vocab in our dataset once it's done.

**Comment by Alexdavv** [comment]
> @dimshitc @cgreich @Alexdavv
> Will you add more? Or can we close this issue?
> I'd like to update the vocab in our dataset once it's done.

Right, we're adding some more. Will publish a special announcement on release.

**Comment by chandryou** [comment]
>Right, we're adding some more. Will publish a special announcement on release.

@Alexdavv  Could you tell me a timeline for that? I need this information for preparing study-a-thon.

**Comment by Alexdavv** [comment]
> > Right, we're adding some more. Will publish a special announcement on release.
> 
> @Alexdavv Could you tell me a timeline for that? I need this information for preparing study-a-thon.

The plan is today.

**Comment by Alexdavv** [comment]
[Here is](https://github.com/OHDSI/Covid-19/wiki/Release) a summary of new concepts added.
So this issue might be closed.
